In [3]:
# ==============================================================================
# 1. СТАНДАРТНЫЕ БИБЛИОТЕКИ (Встроенные в Python)
# ==============================================================================
import joblib
from pathlib import Path
import os
import sys
# ==============================================================================
# 2. СТОРОННИЕ БИБЛИОТЕКИ
# ==============================================================================
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from statsmodels.stats.outliers_influence import variance_inflation_factor
# ==============================================================================
# 3. SCIKIT-LEARN (Preprocessing & Pipeline)
# ==============================================================================
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import  OneHotEncoder, StandardScaler
# ==============================================================================
# 4. ЛОКАЛЬНЫЕ МОДУЛИ 
# ==============================================================================
# 1. Получаем путь к текущей папке (где лежит ноутбук)
current_path = Path(os.getcwd())
PROJECT_ROOT = current_path.parent
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from src.config import *
from src.pipeline import get_pipeline
from src import core
from src.transformers import MissingValueImputer, OrdinalEncoderTransformer, CombinedFeaturesAdded
# ==============================================================================
# 5. НАСТРОЙКИ ПРОЕКТА
# ==============================================================================

# Настройка визуализации 
sns.set_theme(style="whitegrid")
plt.rcParams["figure.figsize"] = (10, 6)
# Чтобы видеть все колонки Pandas
pd.set_option('display.max_columns', None)
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [4]:
df_train = pd.read_csv(TRAIN_DATA)
df_test = pd.read_csv(TEST_DATA)

In [5]:
df_train = core.clean_outliers(df_train, (df_train[(df_train['GrLivArea'] > 4000) & (df_train['SalePrice'] < 250000)].index))
X = df_train.drop(['SalePrice'], axis=1).set_index('Id')
y = core.log_transform_target(df_train['SalePrice'])

In [6]:
y

0       12.247699
1       12.109016
2       12.317171
3       11.849405
4       12.429220
          ...
1455    12.072547
1456    12.254868
1457    12.493133
1458    11.864469
1459    11.901590
Name: SalePrice, Length: 1458, dtype: float64

In [7]:
X.select_dtypes(exclude=np.number)

,MSZoning,Street,Alley,LotShape,LandContour,Utilities,LotConfig,LandSlope,Neighborhood,Condition1,Condition2,BldgType,HouseStyle,RoofStyle,RoofMatl,Exterior1st,Exterior2nd,MasVnrType,ExterQual,ExterCond,Foundation,BsmtQual,BsmtCond,BsmtExposure,BsmtFinType1,BsmtFinType2,Heating,HeatingQC,CentralAir,Electrical,KitchenQual,Functional,FireplaceQu,GarageType,GarageFinish,GarageQual,GarageCond,PavedDrive,PoolQC,Fence,MiscFeature,SaleType,SaleCondition
Id,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
1,RL,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,CollgCr,Norm,Norm,1Fam,2Story,Gable,CompShg,VinylSd,VinylSd,BrkFace,Gd,TA,PConc,Gd,TA,No,GLQ,Unf,GasA,Ex,Y,SBrkr,Gd,Typ,NaN,Attchd,RFn,TA,TA,Y,NaN,NaN,NaN,WD,Normal
2,RL,Pave,NaN,Reg,Lvl,AllPub,FR2,Gtl,Veenker,Feedr,Norm,1Fam,1Story,Gable,CompShg,MetalSd,MetalSd,NaN,TA,TA,CBlock,Gd,TA,Gd,ALQ,Unf,GasA,Ex,Y,SBrkr,TA,Typ,TA,Attchd,RFn,TA,TA,Y,NaN,NaN,NaN,WD,Normal
3,RL,Pave,NaN,IR1,Lvl,AllPub,Inside,Gtl,CollgCr,Norm,Norm,1Fam,2Story,Gable,CompShg,VinylSd,VinylSd,BrkFace,Gd,TA,PConc,Gd,TA,Mn,GLQ,Unf,GasA,Ex,Y,SBrkr,Gd,Typ,TA,Attchd,RFn,TA,TA,Y,NaN,NaN,NaN,WD,Normal
4,RL,Pave,NaN,IR1,Lvl,AllPub,Corner,Gtl,Crawfor,Norm,Norm,1Fam,2Story,Gable,CompShg,Wd Sdng,Wd Shng,NaN,TA,TA,BrkTil,TA,Gd,No,ALQ,Unf,GasA,Gd,Y,SBrkr,Gd,Typ,Gd,Detchd,Unf,TA,TA,Y,NaN,NaN,NaN,WD,Abnorml
5,RL,Pave,NaN,IR1,Lvl,AllPub,FR2,Gtl,NoRidge,Norm,Norm,1Fam,2Story,Gable,CompShg,VinylSd,VinylSd,BrkFace,Gd,TA,PConc,Gd,TA,Av,GLQ,Unf,GasA,Ex,Y,SBrkr,Gd,Typ,TA,Attchd,RFn,TA,TA,Y,NaN,NaN,NaN,WD,Normal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1456,RL,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,Gilbert,Norm,Norm,1Fam,2Story,Gable,CompShg,VinylSd,VinylSd,NaN,TA,TA,PConc,Gd,TA,No,Unf,Unf,GasA,Ex,Y,SBrkr,TA,Typ,TA,Attchd,RFn,TA,TA,Y,NaN,NaN,NaN,WD,Normal
1457,RL,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,NWAmes,Norm,Norm,1Fam,1Story,Gable,CompShg,Plywood,Plywood,Stone,TA,TA,CBlock,Gd,TA,No,ALQ,Rec,GasA,TA,Y,SBrkr,TA,Min1,TA,Attchd,Unf,TA,TA,Y,NaN,MnPrv,NaN,WD,Normal
1458,RL,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,Crawfor,Norm,Norm,1Fam,2Story,Gable,CompShg,CemntBd,CmentBd,NaN,Ex,Gd,Stone,TA,Gd,No,GLQ,Unf,GasA,Ex,Y,SBrkr,Gd,Typ,Gd,Attchd,RFn,TA,TA,Y,NaN,GdPrv,Shed,WD,Normal
1459,RL,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,NAmes,Norm,Norm,1Fam,1Story,Hip,CompShg,MetalSd,MetalSd,NaN,TA,TA,CBlock,TA,TA,Mn,GLQ,Rec,GasA,Gd,Y,FuseA,Gd,Typ,NaN,Attchd,Unf,TA,TA,Y,NaN,NaN,NaN,WD,Normal
1460,RL,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,Edwards,Norm,Norm,1Fam,1Story,Gable,CompShg,HdBoard,HdBoard,NaN,Gd,TA,CBlock,TA,TA,No,BLQ,LwQ,GasA,Gd,Y,SBrkr,TA,Typ,NaN,Attchd,Fin,TA,TA,Y,NaN,NaN,NaN,WD,Normal

In [8]:
cleaner = MissingValueImputer()
df_train_cleaned = cleaner.fit_transform(X)

In [9]:
core.calculate_vif(df_train_cleaned)

c:\Users\ggosh\AI_Work\MLtask\MLtask\project\.venv\Lib\site-packages\statsmodels\stats\outliers_influence.py:197: RuntimeWarning: divide by zero encountered in scalar divide
  vif = 1. / (1. - r_squared_i)

          feature       VIF
8      BsmtFinSF1       inf
9      BsmtFinSF2       inf
10      BsmtUnfSF       inf
11    TotalBsmtSF       inf
15      GrLivArea       inf
14   LowQualFinSF       inf
13       2ndFlrSF       inf
12       1stFlrSF       inf
35         YrSold  22127.98
6    YearRemodAdd  21161.46
5       YearBuilt  17397.45
22   TotRmsAbvGrd     83.25
3     OverallQual     66.47
4     OverallCond     41.53
25     GarageCars     39.99
21   KitchenAbvGr     37.94
24    GarageYrBlt     32.73
26     GarageArea     31.40
20   BedroomAbvGr     31.00
18       FullBath     26.53
1     LotFrontage     17.95
34         MoSold      6.64
0      MSSubClass      4.70
16   BsmtFullBath      3.70
19       HalfBath      3.42
23     Fireplaces      2.99
2         LotArea      2.67
27     WoodDeckSF      1.89
7      MasVnrArea      1.86
28    OpenPorchSF      1.83
29  EnclosedPorch      1.45
17   BsmtHalfBath      1.22
31    ScreenPorch      1.19
32       PoolArea      1.10
30      3SsnPorch      1.04
33        MiscVal      1.03

In [10]:
feat_adder = CombinedFeaturesAdded()
df_transformed = feat_adder.transform(df_train_cleaned)

In [11]:
df_transformed.select_dtypes(exclude=np.number)

,MSSubClass,MSZoning,LotShape,LandContour,LotConfig,LandSlope,Neighborhood,BldgType,HouseStyle,RoofStyle,Exterior2nd,MasVnrType,ExterQual,ExterCond,Foundation,BsmtQual,BsmtCond,BsmtExposure,BsmtFinType1,BsmtFinType2,HeatingQC,CentralAir,Electrical,KitchenQual,Functional,FireplaceQu,GarageType,GarageFinish,GarageQual,GarageCond,PavedDrive,SaleType,SaleCondition
Id,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
1,60,RL,Reg,Lvl,Inside,Gtl,CollgCr,1Fam,2Story,Gable,VinylSd,BrkFace,Gd,TA,PConc,Gd,TA,No,GLQ,Unf,Ex,Y,SBrkr,Gd,Typ,None,Attchd,RFn,TA,TA,Y,WD,Normal
2,20,RL,Reg,Lvl,FR2,Gtl,Veenker,1Fam,1Story,Gable,MetalSd,None,TA,TA,CBlock,Gd,TA,Gd,ALQ,Unf,Ex,Y,SBrkr,TA,Typ,TA,Attchd,RFn,TA,TA,Y,WD,Normal
3,60,RL,IR1,Lvl,Inside,Gtl,CollgCr,1Fam,2Story,Gable,VinylSd,BrkFace,Gd,TA,PConc,Gd,TA,Mn,GLQ,Unf,Ex,Y,SBrkr,Gd,Typ,TA,Attchd,RFn,TA,TA,Y,WD,Normal
4,70,RL,IR1,Lvl,Corner,Gtl,Crawfor,1Fam,2Story,Gable,Wd Shng,None,TA,TA,BrkTil,TA,Gd,No,ALQ,Unf,Gd,Y,SBrkr,Gd,Typ,Gd,Detchd,Unf,TA,TA,Y,WD,Abnorml
5,60,RL,IR1,Lvl,FR2,Gtl,NoRidge,1Fam,2Story,Gable,VinylSd,BrkFace,Gd,TA,PConc,Gd,TA,Av,GLQ,Unf,Ex,Y,SBrkr,Gd,Typ,TA,Attchd,RFn,TA,TA,Y,WD,Normal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1456,60,RL,Reg,Lvl,Inside,Gtl,Gilbert,1Fam,2Story,Gable,VinylSd,None,TA,TA,PConc,Gd,TA,No,Unf,Unf,Ex,Y,SBrkr,TA,Typ,TA,Attchd,RFn,TA,TA,Y,WD,Normal
1457,20,RL,Reg,Lvl,Inside,Gtl,NWAmes,1Fam,1Story,Gable,Plywood,Stone,TA,TA,CBlock,Gd,TA,No,ALQ,Rec,TA,Y,SBrkr,TA,Min1,TA,Attchd,Unf,TA,TA,Y,WD,Normal
1458,70,RL,Reg,Lvl,Inside,Gtl,Crawfor,1Fam,2Story,Gable,CmentBd,None,Ex,Gd,Stone,TA,Gd,No,GLQ,Unf,Ex,Y,SBrkr,Gd,Typ,Gd,Attchd,RFn,TA,TA,Y,WD,Normal
1459,20,RL,Reg,Lvl,Inside,Gtl,NAmes,1Fam,1Story,Hip,MetalSd,None,TA,TA,CBlock,TA,TA,Mn,GLQ,Rec,Gd,Y,FuseA,Gd,Typ,None,Attchd,Unf,TA,TA,Y,WD,Normal
1460,20,RL,Reg,Lvl,Inside,Gtl,Edwards,1Fam,1Story,Gable,HdBoard,None,Gd,TA,CBlock,TA,TA,No,BLQ,LwQ,Gd,Y,SBrkr,TA,Typ,None,Attchd,Fin,TA,TA,Y,WD,Normal

In [12]:
vif_results = core.calculate_vif(df_transformed)
with pd.option_context('display.max_rows', None):
    display(vif_results)

                   feature    VIF
12                 TotalSF  41.61
0              OverallQual  39.84
13               TotalBath  19.38
14  LivingArea_per_Bedroom  11.80
4               GarageArea  10.50
15           UnfBsmt_Ratio   9.66
2               BsmtFinSF1   6.82
25                HouseAge   5.73
26         YearsSinceRemod   3.80
3               Fireplaces   2.64
5               WoodDeckSF   1.87
1               MasVnrArea   1.78
20                HasFence   1.41
29     Is_New_Construction   1.41
6            EnclosedPorch   1.38
28              MoSold_cos   1.31
16     IsNonStandardLayout   1.29
22               IsBadCond   1.26
10                HasAlley   1.24
23   IsNonStandardExterior   1.23
7               IsNearRoad   1.22
30      Is_Distressed_Sale   1.19
11       IsNonStandardRoof   1.12
24    Has_Standard_Heating   1.12
18                 HasPool   1.12
21        Has_LowQual_Area   1.10
9         IsNearPosFeature   1.08
19          HasMiscFeature   1.08
8               IsNearRail   1.06
17            Has3SsnPorch   1.04
27              MoSold_sin   1.03

In [13]:
pd.reset_option('display.max_rows')

In [14]:
df_transformed.columns

Index(['MSSubClass', 'MSZoning', 'LotShape', 'LandContour', 'LotConfig',
       'LandSlope', 'Neighborhood', 'BldgType', 'HouseStyle', 'OverallQual',
       'RoofStyle', 'Exterior2nd', 'MasVnrType', 'MasVnrArea', 'ExterQual',
       'ExterCond', 'Foundation', 'BsmtQual', 'BsmtCond', 'BsmtExposure',
       'BsmtFinType1', 'BsmtFinSF1', 'BsmtFinType2', 'HeatingQC', 'CentralAir',
       'Electrical', 'KitchenQual', 'Functional', 'Fireplaces', 'FireplaceQu',
       'GarageType', 'GarageFinish', 'GarageArea', 'GarageQual', 'GarageCond',
       'PavedDrive', 'WoodDeckSF', 'EnclosedPorch', 'SaleType',
       'SaleCondition', 'IsNearRoad', 'IsNearRail', 'IsNearPosFeature',
       'HasAlley', 'IsNonStandardRoof', 'TotalSF', 'TotalBath',
       'LivingArea_per_Bedroom', 'UnfBsmt_Ratio', 'IsNonStandardLayout',
       'Has3SsnPorch', 'HasPool', 'HasMiscFeature', 'HasFence',
       'Has_LowQual_Area', 'IsBadCond', 'IsNonStandardExterior',
       'Has_Standard_Heating', 'HouseAge', 'YearsSinceRemod', 'MoSold_sin',
       'MoSold_cos', 'Is_New_Construction', 'Is_Distressed_Sale'],
      dtype='str')

In [15]:
final_pipeline = get_pipeline()

final_pipeline.fit(X, y)

Pipeline(steps=[('imputer', MissingValueImputer()),
                ('features', CombinedFeaturesAdded()),
                ('encoding',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('ord',
                                                  OrdinalEncoderTransformer(column_mappings={'BsmtCond': {'Ex': 5,
                                                                                                          'Fa': 2,
                                                                                                          'Gd': 4,
                                                                                                          'NA': 0,
                                                                                                          'None': 0,
                                                                                                          'Po': 1,
                                                                                                          'TA': 3},
                                                                                             'BsmtExposure': {False: 1,
                                                                                                              'Av': 3,
                                                                                                              'Gd': 4,
                                                                                                              'Mn': 2,
                                                                                                              'NA': 0,
                                                                                                              'None': 0},
                                                                                             'BsmtFinType1': {'AL...
                                                   'HeatingQC', 'FireplaceQu',
                                                   'GarageCond', 'BsmtExposure',
                                                   'BsmtFinType1',
                                                   'BsmtFinType2', 'LotShape',
                                                   'LandSlope', 'Electrical',
                                                   'Functional', 'GarageFinish',
                                                   'PavedDrive',
                                                   'CentralAir']),
                                                 ('cat',
                                                  OneHotEncoder(handle_unknown='ignore',
                                                                sparse_output=False),
                                                  <sklearn.compose._column_transformer.make_column_selector object at 0x0000029AB8901490>)])),
                ('scaler', StandardScaler())])

In [16]:
model_path = FEATURE_ENG_DIR / "final_pipeline.joblib"
joblib.dump(final_pipeline, model_path)

feature_names = final_pipeline.get_feature_names_out()
feature_path = FEATURE_ENG_DIR / 'feature_names.joblib'
joblib.dump(feature_names, feature_path)
print(f'Файл сохранен')

Файл сохранен